Refactor gcp cluster instance
IBM/ibm-spectrum-scale-cloud-install pull request #350
Opened 2023-04-04 03:32 UTC by praveenramuu

- refactor gcp instance to move count to resource level
 - add default to null for input variables and change variable names

2023-04-04 09:03 UTC, sasikeda commented on resources/gcp/compute/vm_instance/vm_instance.tf
>  }
I think zone needs to be delete

2023-04-04 09:26 UTC, sasikeda requested changes

2023-04-04 09:26 UTC, sasikeda commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +  block_device_names = ["/dev/sdb", "/dev/sdc", "/dev/sdd", "/dev/sdf", "/dev/sdg",
Ideally, 256 attachments are supported. But we can stick to above.

2023-04-04 09:26 UTC, sasikeda commented on resources/gcp/compute/vm_instance/vm_instance.tf
>    tags                      = var.vm_instance_tags
No need of tags

2023-04-04 09:26 UTC, sasikeda commented on resources/gcp/compute/vm_instance/vm_instance.tf
>    description = "GCP service account e-mail address."
rename operator_email to service_email

2023-04-04 09:26 UTC, sasikeda commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +    subnetwork = local.vm_configuration[count.index].subnet
is there a need of scratch disk loop ?

2023-04-04 09:26 UTC, sasikeda commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +  instance   = google_compute_instance.scale_instance[local.disk_configuration[count.index].index].instance_id
instance_id ?, from doc it suggests name or self_link
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_attached_disk

2023-04-04 09:26 UTC, sasikeda commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +  value = google_compute_instance.scale_instance[*].instance_id
kindly use self_link

2023-04-04 09:26 UTC, sasikeda commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +  value = google_compute_disk.data_disk[*].zone
subnet_name --> but o/p is showing zone ?

2023-04-04 09:26 UTC, sasikeda commented on gcp_scale_templates/sub_modules/instance_template/main.tf
> +  total_local_ssd_disks  = var.data_disk_type == "local-ssd" ? var.block_devices_per_storage_instance : 0
kindly use seperate variables for local_ssd_disks and persistent_disks, as from cloudkit we control then via different variables.

2023-04-04 09:26 UTC, sasikeda commented on gcp_scale_templates/sub_modules/instance_template/main.tf
> +  total_persistent_disks        = 5
we are creating 5 persistent disks here ?
it should be 1 disk with 5GB size

2023-04-04 09:26 UTC, sasikeda commented on gcp_scale_templates/sub_modules/instance_template/main.tf
> +  vpc_availability_zones        = var.vpc_availability_zones
it will be placed in 3rd az. not all vpc zones needs to be provided.

2023-04-04 13:07 UTC, praveenramuu commented on resources/gcp/compute/vm_instance/vm_instance.tf
>  }
Thanks sasi , done

2023-04-04 13:07 UTC, praveenramuu commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +  block_device_names = ["/dev/sdb", "/dev/sdc", "/dev/sdd", "/dev/sdf", "/dev/sdg",
Thanks sasi

2023-04-04 13:08 UTC, praveenramuu commented on resources/gcp/compute/vm_instance/vm_instance.tf
>    description = "GCP service account e-mail address."
Thanks done

2023-04-04 13:12 UTC, praveenramuu commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +    subnetwork = local.vm_configuration[count.index].subnet
Thanks , It's already exists at line 203 with dynamic "scratch_disk" block

2023-04-04 13:12 UTC, praveenramuu commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +  value = google_compute_instance.scale_instance[*].instance_id
Thanks sasi , done

2023-04-04 13:12 UTC, praveenramuu commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +  value = google_compute_disk.data_disk[*].zone
Thanks sasi , changed to data_disk_zone :-)

2023-04-04 13:16 UTC, praveenramuu commented on resources/gcp/compute/vm_instance/vm_instance.tf
> +  instance   = google_compute_instance.scale_instance[local.disk_configuration[count.index].index].instance_id
Thanks sasi , both works name as well as instance_id .
instance_id is used for instance param in above mentioned doc at 'example usage'

2023-04-04 13:16 UTC, praveenramuu commented on gcp_scale_templates/sub_modules/instance_template/main.tf
> +  total_local_ssd_disks  = var.data_disk_type == "local-ssd" ? var.block_devices_per_storage_instance : 0
Thanks sasi , done , introduced block_devices_per_storage_instance & scratch_devices_per_storage_instance

2023-04-04 13:17 UTC, praveenramuu commented on gcp_scale_templates/sub_modules/instance_template/main.tf
> +  total_persistent_disks        = 5
Thanks done

2023-04-04 13:17 UTC, praveenramuu commented on gcp_scale_templates/sub_modules/instance_template/main.tf
> +  vpc_availability_zones        = var.vpc_availability_zones
Thanks done sasi

2023-04-04 13:22 UTC, praveenramuu commented on resources/gcp/compute/vm_instance/vm_instance.tf
>    tags                      = var.vm_instance_tags
I will raise new PR for this removal of tag

2023-04-05 09:12 UTC, sasikeda commented
Kindly change main.tf (lines), inoder to work with null.

```
locals {
  cluster_type = (
    (length(var.vpc_storage_cluster_private_subnets) > 0 && length(var.vpc_compute_cluster_private_subnets) == 0) ? "storage" :
    (length(var.vpc_storage_cluster_private_subnets) == 0 && length(var.vpc_compute_cluster_private_subnets) > 0) ? "compute" :
    (length(var.vpc_storage_cluster_private_subnets) > 0 && length(var.vpc_compute_cluster_private_subnets) > 0) ? "combined" : "none"
  )
```
to

```
cluster_type = (
    (var.vpc_storage_cluster_private_subnets != null && var.vpc_compute_cluster_private_subnets == null) ? "storage" :
    (var.vpc_storage_cluster_private_subnets == null && var.vpc_compute_cluster_private_subnets != null) ? "compute" :
    (var.vpc_storage_cluster_private_subnets != null && var.vpc_compute_cluster_private_subnets != null) ? "combined" : "none"
  )
```

2023-04-05 09:26 UTC, sasikeda commented
The conditions defined for vpc_subnets in the compute only, storage only, tie-breaker modules break if we choose to deploy only compute or only storage;
```
Error: Iteration over null value
│
│   on ../../../resources/gcp/compute/vm_instance/vm_instance.tf line 142, in locals:
│  142:   vm_configuration    = flatten([for zone_name in var.vpc_availability_zones : [for network in var.vpc_subnets : [for i in range(var.total_cluster_instances) : {zone = zone_name , subnet = network, vm_name = "${var.instance_name}-${i}"}]]])
│     ├────────────────
│     │ var.vpc_subnets is null
│
│ A null value cannot be used as the collection in a 'for' expression.
```

2023-04-05 16:23 UTC, praveenramuu commented
> The conditions defined for vpc_subnets in the compute only, storage only, tie-breaker modules break if we choose to deploy only compute or only storage;
> 
> ```
> Error: Iteration over null value
> │
> │   on ../../../resources/gcp/compute/vm_instance/vm_instance.tf line 142, in locals:
> │  142:   vm_configuration    = flatten([for zone_name in var.vpc_availability_zones : [for network in var.vpc_subnets : [for i in range(var.total_cluster_instances) : {zone = zone_name , subnet = network, vm_name = "${var.instance_name}-${i}"}]]])
> │     ├────────────────
> │     │ var.vpc_subnets is null
> │
> │ A null value cannot be used as the collection in a 'for' expression.
> ```
Thanks sasi , it works if we pass empty array i.e, [] for inputs vpc_storage_cluster_private_subnets/vpc_compute_cluster_private_subnets. but yes for null value it fails which I have not unit tested  for this scenario.  Added code now to handle the null for input variables.

2023-04-05 16:24 UTC, praveenramuu commented
> Kindly change main.tf (lines), inoder to work with null.
> 
> ```
> locals {
>   cluster_type = (
>     (length(var.vpc_storage_cluster_private_subnets) > 0 && length(var.vpc_compute_cluster_private_subnets) == 0) ? "storage" :
>     (length(var.vpc_storage_cluster_private_subnets) == 0 && length(var.vpc_compute_cluster_private_subnets) > 0) ? "compute" :
>     (length(var.vpc_storage_cluster_private_subnets) > 0 && length(var.vpc_compute_cluster_private_subnets) > 0) ? "combined" : "none"
>   )
> ```
> 
> to
> 
> ```
> cluster_type = (
>     (var.vpc_storage_cluster_private_subnets != null && var.vpc_compute_cluster_private_subnets == null) ? "storage" :
>     (var.vpc_storage_cluster_private_subnets == null && var.vpc_compute_cluster_private_subnets != null) ? "compute" :
>     (var.vpc_storage_cluster_private_subnets != null && var.vpc_compute_cluster_private_subnets != null) ? "combined" : "none"
>   )
> ```

Thanks changed sasi

2023-04-06 10:06 UTC, sasikeda commented
Looks the new changes, is causing count to multiple. Kindly request to verify, maybe my test could be incorrect.

2023-04-07 10:27 UTC, sasikeda approved these changes

2023-04-07 10:28 UTC, merged